id: AC22584EF
title: Descent of the Compassionate Blessings of King Gesar, Great Lion of this World
type: translation
pechas:
- I12132BD2
- I050EEB7B
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2023-01-04 13:07:27.722285
  last_modified_at: 2023-01-04 13:07:27.722293
  collections:
  - Mipham Rinpoche Series
  - Works of Tibetan Masters
alignment_to_base:
  I12132BD2/F88B: 076C
  I050EEB7B/8A0C: 076C
